spring:
  config:
    activate:
      on-profile: dev
connector:
  private_key_name: connector_private_dev.pem
  priora:
    app_code: spring_bank_ob
    app_id: Kwk9gEHCs5kMY-tG6COr8A
    app_secret: RCeHPhFVv6y-zB4OysBeWFYrQjNRDnSuBWak9qI8Vc4
    base_url: https://priora.banksalt.com/
    public_key_name: priora_public_dev.pem

---
spring:
  config:
    activate:
      on-profile: prod
connector:
  private_key_name: connector_private_prod.pem
  priora:
    app_code: spring_bank_ob
    app_id: Kwk9gEHCs5kMY-tG6COr8A
    app_secret: RCeHPhFVv6y-zB4OysBeWFYrQjNRDnSuBWak9qI8Vc4
    base_url: https://priora.saltedge.com/
    public_key_name: priora_public_prod.pem
